// Copyright © 2025-2026 Prabhjot Singh Sethi, All Rights reserved
// Author: Prabhjot Singh Sethi <prabhjot.sethi@gmail.com>

// Initial reference and motivation taken from
// https://gitlab.com/project-emco/core/emco-base/-/blob/main/src/orchestrator/pkg/infra/db

package db

import (
	"context"
	"reflect"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// IndexType represents the sort order for an index field.
type IndexType int

const (
	IndexAscending  IndexType = 1
	IndexDescending IndexType = -1
)

// IndexField represents a single field within an index definition.
type IndexField struct {
	Field     string
	IndexType IndexType
}

// IndexDefinition describes an index to be created on a collection.
type IndexDefinition struct {
	// Fields specifies the index key fields and their sort order.
	Fields []IndexField
	// Unique enforces uniqueness on the indexed fields.
	Unique bool
	// Sparse only indexes documents that contain the indexed fields.
	// Documents missing the field are excluded from the index.
	Sparse bool
	// TTL sets an expiration duration for documents in the collection.
	// MongoDB automatically deletes documents after this duration,
	// measured from the indexed field's value (must be a date field).
	// Zero value means no TTL.
	TTL time.Duration
	// Name is an optional name for the index. Auto-generated by MongoDB if empty.
	Name string
}

// UpdateSpec describes a conditional update of one document. Each part is an
// encodable value, as data is for UpdateOne; nil or empty parts are left out.
type UpdateSpec struct {
	// Match holds conditions ANDed with {_id: key}; nil means the key alone.
	Match any

	// Set, Inc and Unset become $set, $inc and $unset. At least one must
	// carry something to write.
	//
	// Match, Set and Inc are each encoded once, exactly as given, and those
	// bytes are sent: one that encodes to an empty document counts as
	// absent, and one that cannot be encoded is InvalidArgument. An encoder
	// declared on a pointer type runs only when a pointer is given.
	Set   any
	Inc   any
	Unset []string
}

// WatchCallbackfn responsible for
type WatchCallbackfn func(op string, key any)

// interface definition for a collection in store
type StoreCollection interface {
	// Set KeyType for the collection, this is not mandatory
	// while the key type will be used by the interface implementer
	// mainly for Watch Callback for providing decoded key, if not
	// set watch will be working with the default decoders of
	// interface implementer
	// only pointer key type is supported as of now
	// returns error if the key type is not a pointer
	SetKeyType(keyType reflect.Type) error

	// insert one entry to the collection for the given key and data
	InsertOne(ctx context.Context, key any, data any) error

	// update one entry in the collection for the given key and data
	// if upsert flag is set, it would insert an entry if it doesn't
	// exist while updating
	UpdateOne(ctx context.Context, key any, data any, upsert bool) error

	// UpdateOneWithSpec applies a conditional update to the one document with
	// the given key, never inserting. It reports whether a document matched
	// the key and spec.Match. With no Match, a missing document is a NotFound
	// error, as for UpdateOne; with a Match, it is false, because "absent"
	// and "condition did not hold" are the same answer to the caller.
	UpdateOneWithSpec(ctx context.Context, key any, spec UpdateSpec) (bool, error)

	// Find one entry from the store collection for the given key, where the data
	// value is returned based on the object type passed to it
	FindOne(ctx context.Context, key any, data any) error

	// Find multiple entries from the store collection for the given filter, where the data
	// value is returned as a list based on the object type passed to it
	FindMany(ctx context.Context, filter any, data any, opts ...any) error

	// Return count of entries matching the provided filter
	Count(ctx context.Context, filter any) (int64, error)

	// remove one entry from the collection matching the given key
	DeleteOne(ctx context.Context, key any) error

	// Delete Many entries matching the delete criteria
	// returns number of entries deleted and if there is any error processing the request
	DeleteMany(ctx context.Context, filter any) (int64, error)

	// watch allows getting notified whenever a change happens to a document
	// in the collection
	// allow provisiong for a filter to be passed on, where the callback
	// function to receive only conditional notifications of the events
	// listener is interested about
	Watch(ctx context.Context, filter any, cb WatchCallbackfn) error

	// Aggregate runs a MongoDB aggregation pipeline against the collection
	// and decodes all result documents into the provided result pointer
	// (must be a pointer to a slice). Cursor lifecycle is managed internally.
	Aggregate(ctx context.Context, pipeline any, result any, opts ...any) error

	// EnsureIndexes creates the specified indexes on the collection if they
	// don't already exist. This operation is idempotent.
	EnsureIndexes(ctx context.Context, indexes []IndexDefinition) error

	startEventLogger(ctx context.Context, eventType reflect.Type, timestamp *bson.Timestamp) error
}

// ClientLifetime is implemented by a collection whose client can be
// closed. Lifetime returns a context that ends when that client is
// closed, so work started for the collection in the background can end
// with the client. It is optional: a StoreCollection that does not
// implement it gives such work no end of its own.
type ClientLifetime interface {
	Lifetime() context.Context
}

// interface definition for a store, responsible for holding group
// of collections
type Store interface {
	// Gets collection corresponding to the collection name
	GetCollection(col string) StoreCollection

	// Gets Name of the database corresponding to the store
	Name() string
}

// interface definition for Client corresponding to a store and
type StoreClient interface {
	// Get the Data Store interface given the client interface
	GetDataStore(dbName string) Store

	// Gets collection corresponding to the collection name inside
	// the requested database name
	GetCollection(dbName, col string) StoreCollection

	// Health Check, if the Store is connectable and healthy
	// returns the status of health of the server by means of
	// error if error is nil the health of the DB store can be
	// considered healthy
	HealthCheck(ctx context.Context) error
}
